### get info
GET http://localhost:3001/api/blogs/info

### get single resource (ERS)
GET http://localhost:3001/api/blogs/66d05e16d407cb463574517c

### get single resource => 404 not found(id valid)
GET http://localhost:3001/api/blogs/66d05e16d407cb4635745173

###get single resource => 400 (id invalid)
GET http://localhost:3001/api/blogs/66d05e16d407cb463574517c3

### get all 
GET http://localhost:3001/api/blogs

### create resource
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QyIiwiaWQiOiI2NmRkNDYxOTFkZThlNmFmNzI2MWJjZjMiLCJpYXQiOjE3MjU4MjAzOTQsImV4cCI6MTcyNTgyMzk5NH0.TAHCCWN9OQXr5M0l9zxcbeecUDj1B_m4A5gF61yXPoc

{
    "title": "t2.1",
    "author": "a2.1",
    "url": "https://u2.1.blog/",
    "likes":2.1,
    "userId": "66dd46191de8e6af7261bcf3"
}

### update resource
PUT http://localhost:3001/api/blogs/66d47723d3fb328d9c2931b8
Content-Type: application/json

{
    "title": "Shtetl-Optimized1",
    "author": "Scott Aaronson",
    "url": "https://scottaaronson.blog/",
    "likes":5641
}

### delete resource
DELETE http://localhost:3001/api/blogs/66d47674ec685c792da7948b

### delete single resource => 404 not found(id valid)
DELETE  http://localhost:3001/api/blogs/66d05e16d407cb4635745173

### delete single resource => 400 (id invalid)
DELETE  http://localhost:3001/api/blogs/66d05e16d407cb463574517c3