### get info
GET http://localhost:3001/api/blogs/info

### get single resource (ERS)
GET http://localhost:3001/api/blogs/66d05e16d407cb463574517c

### get single resource => 404 not found(id valid)
GET http://localhost:3001/api/blogs/66d05e16d407cb4635745173

###get single resource => 400 (id invalid)
GET http://localhost:3001/api/blogs/66d05e16d407cb463574517c3

### get all 
GET http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QzIiwiaWQiOiI2NmRlMmMxZDg0MjA3NTYxM2E1MGYzYjciLCJpYXQiOjE3MjU4NDAwODIsImV4cCI6MTcyNTg0MzY4Mn0.SYi3NCWQ_jQylm82r1v2YZlol-wpRW090W2eF8jAiAg

### create resource
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QzIiwiaWQiOiI2NmRlMmMxZDg0MjA3NTYxM2E1MGYzYjciLCJpYXQiOjE3MjU4NDAwODIsImV4cCI6MTcyNTg0MzY4Mn0.SYi3NCWQ_jQylm82r1v2YZlol-wpRW090W2eF8jAiAg

{
    "title": "t3.3",
    "author": "a3.3",
    "url": "https://u3.3.blog/",
    "likes":3.3
}

### update resource
PUT http://localhost:3001/api/blogs/66d47723d3fb328d9c2931b8
Content-Type: application/json

{
    "title": "Shtetl-Optimized1",
    "author": "Scott Aaronson",
    "url": "https://scottaaronson.blog/",
    "likes":5641
}

### delete resource
DELETE http://localhost:3001/api/blogs/66de3e19910bba84b9248216
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QzIiwiaWQiOiI2NmRlMmMxZDg0MjA3NTYxM2E1MGYzYjciLCJpYXQiOjE3MjU4NDAwODIsImV4cCI6MTcyNTg0MzY4Mn0.SYi3NCWQ_jQylm82r1v2YZlol-wpRW090W2eF8jAiAg

### delete single resource => 404 not found(id valid)
DELETE  http://localhost:3001/api/blogs/66d05e16d407cb4635745173

### delete single resource => 400 (id invalid)
DELETE  http://localhost:3001/api/blogs/66d05e16d407cb463574517c3